### ISSUE TITLE
MDNS setting flips back to "On"

### ISSUE THREAD

**Issue by msbannert** [InnuendoPi/Spundomat#2]
If you disable the MDNS and restart the device, then the MDNS setting flips back to "on".

Seen with V2.62

Looks like there is an issue with the deserialisation of the setting, see also https://arduinojson.org/v6/api/jsonvariant/or/#pitfall-%EF%B8%8F

**Comment by InnuendoPi** [comment]
Please try latest 2.64. Feedback welcome

**Comment by msbannert** [comment]
V2.64 works fine, the issue is fixed.

Thanks a lot !
